services:
  db:
    image: postgres:16
    container_name: postgres-db3
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: owokequ
      POSTGRES_DB: db
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis
    container_name: redis3
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq3
    ports:
      - '5672:5672' 
      - '15672:15672' 
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: root
volumes:
  pgdata:
  redis_data:
